#!/bin/bash

mkdir -p assets
GOOS=linux GOARCH=amd64 go build -o assets/in ./cmd/in
GOOS=linux GOARCH=amd64 go build -o assets/out ./cmd/out
GOOS=linux GOARCH=amd64 go build -o assets/check ./cmd/check
